/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycafe;

//import com.itextpdf.text.DocumentException;
import java.awt.HeadlessException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author TOMMOGO
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        txtcn.setEditable(false);
        txtcid.setEditable(false);
        txtcod.setEditable(false);
        txtcmn.setEditable(false);
        txtp.setEditable(false);
        txtnds.setEditable(false);
        txttacfr.setEditable(false);
        txtmail.setEditable(false);

    }
    int ID = 0;
    String Query;
    String RoomType;
    String Bed;
    String RoomNo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcn = new javax.swing.JTextField();
        txtcid = new javax.swing.JTextField();
        txtcod = new javax.swing.JTextField();
        txtcmn = new javax.swing.JTextField();
        txtp = new javax.swing.JTextField();
        txtnds = new javax.swing.JTextField();
        txttacfr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_1.png"))); // NOI18N
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 27, 24));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("CheckOutDate");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Customer Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Check In Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(102, 0, 0));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        txtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Nationality", "Gender", "Email", "ID Proof", "Addressl", "CheckIn Date", "RoomNumber", "Bed", "RoomType", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(txtTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1060, 200));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Number Of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Total Amount Collect From Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        txtcn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcn.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, -1));

        txtcid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcid.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 130, -1));

        txtcod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcod.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 140, -1));

        txtcmn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcmn.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtcmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 150, -1));

        txtp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtp.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, -1));

        txtnds.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnds.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtnds, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 160, -1));

        txttacfr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttacfr.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txttacfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmail.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 140, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 0));
        jButton4.setText("CLear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = select.getData("select *from customer where CheckOut is NULL");
        DefaultTableModel model = (DefaultTableModel) txtTable.getModel();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13),});
            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String RoomNo = jTextField1.getText();
        try {
            ResultSet rs = select.getData("select *from customer where RoomNo='" + RoomNo + "' and Checkout is null");
            if (rs.next()) {
                jTextField1.setEditable(false);
                ID = rs.getInt(1);
                txtcn.setText(rs.getString(2));
                txtcid.setText(rs.getString(9));
                txtcmn.setText(rs.getString(3));
                txtp.setText(rs.getString(13));
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal = Calendar.getInstance();
                txtcod.setText(myFormat.format(cal.getTime()));
                String dateBeforeString = rs.getString(9);
                java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                String dateAfterString = myFormat.format(cal.getTime());
                java.util.Date dateAfter = myFormat.parse(dateAfterString);
                long difference = dateAfter.getTime() - dateBefore.getTime();
                int NoOfDaySaty = (int) (difference / (1000 * 60 * 60 * 24));
                if (NoOfDaySaty == 0) {
                    NoOfDaySaty = 1;
                }
                txtnds.setText(String.valueOf(NoOfDaySaty));
                float Price = Float.parseFloat(txtnds.getText());
                txttacfr.setText(String.valueOf(NoOfDaySaty * Price));
                txtmail.setText(rs.getString(6));
                RoomType = rs.getString(12);
                Bed = rs.getString(11);
            } else {
                JOptionPane.showMessageDialog(null, "RoomNumber is not Booked or RoomNumber does not Exist");
            }
        } catch (HeadlessException | NumberFormatException | SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Name = txtcn.getText();
        String MobileNumber = txtcmn.getText();
        String Email = txtmail.getText();
        String Checkout = txtcod.getText();
        String NumberofDaysStay = txtnds.getText();
        String TotalAmount = txttacfr.getText();
        RoomNo = jTextField1.getText();
        Query = "update customer set NumberofDaysStay='" + NumberofDaysStay + "',TotalAmount='" + TotalAmount + "',Checkout='" + Checkout + "'where ID='" + ID + "'";
        InsertUpdatedelete.setData(Query, "");
        Query = "update Room set Status='Not Booked' where RoomNo='" + RoomNo + "'";
        InsertUpdatedelete.setData(Query, "");
        String path = "E:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + ID + ".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                         Welcome to My Cafe/Hotel");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("***************************************************************************************************");
            doc.add(paragraph2);
            Paragraph paragraph3 = new Paragraph("\tBill ID:" + ID + "\nCustomer Details:\nName:" + Name + "\nMobileNumber" + MobileNumber + "\n Email:" + Email + "\n");
            doc.add(paragraph3);
            doc.add(paragraph2);
            Paragraph paragraph4 = new Paragraph("\tRoomDetails:\nNumber:" + jTextField1.getText() + "\nType:" + RoomType + "\n Bed:" + Bed + "\nPricePerday: " + txtp.getText() + "");
            doc.add(paragraph4);
            doc.add(paragraph2);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("CheckInDate   " + txtcid.getText());
            tb1.addCell("CheckOutDate   " + Checkout);
            tb1.addCell("Number of days stay   " + NumberofDaysStay);
            tb1.addCell("Total Amount Paid  " + TotalAmount);
            doc.add(tb1);
            doc.add(paragraph2);
            Paragraph paragraph5 = new Paragraph("Thank you for Visiting us!!!welcome again");
            doc.add(paragraph5);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int y = JOptionPane.showConfirmDialog(null, "Confirm you want to print bill?", "select", JOptionPane.YES_NO_OPTION);
        if (y == 0) {
            try {
                if ((new File("E:\\")).exists()) {
                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler E:\\" + ID + ".pdf");
                } else {
                    System.out.println("File Does not Exist!!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerCheckOut().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable txtTable;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcmn;
    private javax.swing.JTextField txtcn;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnds;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txttacfr;
    // End of variables declaration//GEN-END:variables
}
