/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycafe;

import javax.swing.JOptionPane;
import java.sql.*;
import project.select;

/**
 *
 * @author TOMMOGO
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        signupbtn = new javax.swing.JButton();
        fgbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        Admbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b12.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(660, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 261, -1));

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 272, -1));

        loginbtn.setBackground(new java.awt.Color(255, 51, 51));
        loginbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(204, 0, 0));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        signupbtn.setBackground(new java.awt.Color(255, 51, 51));
        signupbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(204, 0, 0));
        signupbtn.setText("Sign up");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        getContentPane().add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        fgbtn.setBackground(new java.awt.Color(255, 51, 51));
        fgbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fgbtn.setForeground(new java.awt.Color(204, 0, 0));
        fgbtn.setText("Forget Password");
        fgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgbtnActionPerformed(evt);
            }
        });
        getContentPane().add(fgbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 0, 50, 30));

        Admbtn.setBackground(new java.awt.Color(255, 0, 51));
        Admbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Admbtn.setForeground(new java.awt.Color(204, 0, 0));
        Admbtn.setText("Login As Admin");
        Admbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Admbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b12.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int y=JOptionPane.showConfirmDialog(null,"Confirm you want to exit!!?","Thank you",JOptionPane.YES_NO_OPTION);
if(y==0)
{
    System.exit(0);
    
}
    }//GEN-LAST:event_exitbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        int check=0;
        String Email=txtEmail.getText();
        String Password=txtpass.getText();
        if (Email.equals("")||Password.equals(""))
        {
            check=1;
            JOptionPane.showMessageDialog(null, "Every Field is Required");
        }
        else if(Email.equals("hms")&& Password.equals("admin"))
        {
            check=1;
            setVisible(false);
            new Adminhome().setVisible(true);
        }
        else
        {
            ResultSet rs=select.getData("select *from users where email='"+Email+"'and Password='"+Password+"'");
            try
            {
                if (rs.next())
                {
                    check=1;
                    if(rs.getString(7).equals("true"))
                    {
                        setVisible(false);
                        new HomePage().setVisible(true);
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Wait for Admin Approval");
                }
            }
            catch(Exception e){ 
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (check==0)
            JOptionPane.showMessageDialog(null, "Incorrect User Email or Password");
    }//GEN-LAST:event_loginbtnActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_signupbtnActionPerformed

    private void fgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ForgetPassword p=new  ForgetPassword();
        p.setVisible(true);
        //new ForgetPassword().setVisible(true);
    }//GEN-LAST:event_fgbtnActionPerformed

    private void AdmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmbtnActionPerformed
        // TODO add your handling code here:
        new Adminhome().setVisible(true);
    }//GEN-LAST:event_AdmbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton fgbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
